
authEnabled: true

logging:
    level: INFO
    loggers:
      "org.zenoss.app.pipelineservice": DEBUG
      "org.zenoss.datapipeline": DEBUG
    #  "org.zenoss.databus": INFO
      
    appenders:
      - type: console
        threshold: ALL
        
      - type: file
        currentLogFilename: ./log/pipelineservice.log
        archivedLogFilenamePattern: ./log/pipelineservice-%d.log.gz
        archivedFileCount: 5
        timeZone: UTC
        threshold: ALL

proxyConfiguration:
  hostname: 127.0.0.1
  port: 8080
server:
  applicationConnectors:
    - type: http
      port: 8095
    - type: https
      port: 8096
      keyStorePath: etc/datapipeline-service/cert/ssl.pfx
      keyStorePassword: zapp_pass
      keyStoreType:     pkcs12
      validateCerts: false
  adminConnectors:
    - type: http
      port: 58095
    - type: https
      port: 58096
      keyStorePath: etc/datapipeline-service/cert/ssl.pfx
      keyStorePassword: zapp_pass
      keyStoreType:     pkcs12
      validateCerts: false



#webSocketConfiguration:
#    maxTextMessageSize: 10485760

pipelineService:
    configFile: etc/datapipeline-service/PipelineFramework.properties
    poolSize: 5
    # paths to (non-default) directories to search for various resources
    directoryList: 
      - /opt/zenoss/etc/datapipeline/pipelines
      - /var/zenoss/datapipeline/etc/pipelines
 # - hdfs:///some/global/config
 