server:
  applicationConnectors:
  - type: http
    port: 8090
  adminConnectors:
  - type: http
    port: 58090

metricPublish:
  producerConfigFile: etc/dataconsumer-api/ProducerDefaults.properties
  brokers: 172.31.43.108:9092,172.31.43.216:9092,172.31.45.107:9092
  topic: metric-raw-any
  schemaRegistryUrl: http://172.31.43.108:8081,http://172.31.43.216:8081,http://172.31.45.107:8081

metricCatalog:
  host: http://localhost:8060

logging:
  level: INFO
  loggers:
    org.zenoss.app.dataconsumer.api.metrics.remote: DEBUG

swagger:
  resourcePackage: org.zenoss.app.dataconsumer.api.metrics.remote
  title: Ingest API
  version: v1
  description: Dynamic Metric Ingestion API
  contact: info@zenoss.com
  license: Apache 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0

proxyConfiguration:
  hostname: 127.0.0.1
  port: 8080
