log:
  level: info
http:
  port: 9237
zing:
  url: ws://172.17.0.1:8000
model-ingest: 
  path: /api/model/ingest
  enabled: true
metric-ingest:
  path: /api/metrics/ingest
  enabled: true
pubsub:
  project: zing-testing
  tenant: ""
  source: ""
  host-port: ""
  metric-topic: metric-raw-rm
  model-topic: model-raw-rm

