log:
  level: info
http:
  port: 9237
pubsub:
  project: {{getContext . "cse.project"}}
  tenant: {{getContext . "cse.tenant"}}
  source: {{getContext . "cse.source"}}
  metric-topic: metric-raw-rm
  model-topic: model-raw-rm
  # use-emulator: false
  # host-port: <emulator-ip:emulator-port>
